services:
  - type: web
    name: zak-nsfw-gen-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: BOT_TOKEN
      - key: REPLICATE_TOKEN